"""order

Revision ID: 08acf991fb25
Revises: 4c4c9c7f8e24
Create Date: 2023-01-31 00:14:30.786942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08acf991fb25'
down_revision = '4c4c9c7f8e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('button', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('button', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('button', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('button', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('button', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('button', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('button', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('button', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
