"""empty message

Revision ID: 28d38f9e2e65
Revises: 670f4caac7dd
Create Date: 2023-02-02 22:05:57.397476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d38f9e2e65'
down_revision = '670f4caac7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('button', sa.Column('order', sa.Integer(), nullable=False))
    op.alter_column('button', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('button', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('button', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('button', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('button', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('category', sa.Column('order', sa.Integer(), nullable=False))
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('category', 'order')
    op.alter_column('button', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('button', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('button', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('button', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('button', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('button', 'order')
    # ### end Alembic commands ###
