"""Init

Revision ID: 4c4c9c7f8e24
Revises: 670f4caac7dd
Create Date: 2023-01-24 13:52:54.862638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c4c9c7f8e24'
down_revision = '670f4caac7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('button', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('category', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('items', postgresql.ARRAY(postgresql.BYTEA()), autoincrement=False, nullable=True))
    op.drop_column('category', 'order')
    op.drop_column('button', 'order')
    # ### end Alembic commands ###
